---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: 您必須瞭StorageGRID 解升級過程中、您的不知道哪些系統會受到影響。 
---
= 系統在升級期間的影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須瞭StorageGRID 解升級過程中、您的不知道哪些系統會受到影響。



== 不中斷升級StorageGRID

整個升級過程中、這個系統可以從用戶端應用程式擷取及擷取資料。StorageGRID如果您核准所有類型相同的節點進行升級（例如儲存節點）、則節點會一次關閉一個節點、因此當某種類型的所有網格節點或所有網格節點都無法使用時、就不會有任何時間。

為了確保持續可用、請確保 ILM 原則包含指定儲存每個物件多個複本的規則。您也必須確保所有外部S3或Swift用戶端均設定為傳送要求至下列其中一項：

* 高可用度（ HA ）群組虛擬 IP 位址
* 高可用度協力廠商負載平衡器
* 每個用戶端有多個閘道節點
* 每個用戶端有多個儲存節點




== 應用裝置韌體已升級

在 StorageGRID 11.7 升級期間：

* 所有 StorageGRID 應用裝置節點都會自動升級至 StorageGRID 應用裝置安裝程式韌體 3.7 版。
* SG6060 和 SGF6024 應用裝置會自動升級至 BIOS 韌體版本 3B07.EX 和 BMC 韌體版本 3.97.07 。
* SG100 和 SG1000 應用裝置會自動升級至 BIOS 韌體版本 3B12.EC 和 BMC 韌體版本 4.71.07 。




== 可能會觸發警示

當服務啟動和停止時、StorageGRID 以及當作業系統以混合版本環境運作時、可能會觸發警示（部分網格節點執行較早版本、而其他節點則已升級至較新版本）。升級完成後、可能會觸發其他警示。

例如、當服務停止時、您可能會看到 * 無法與 node* 通訊警示、或者當某些節點已升級至 StorageGRID 11.7 、但其他節點仍在執行 StorageGRID 11.6 時、您可能會看到 * Cassandra 通訊錯誤 * 警示。一般而言、這些警示會在升級完成時清除。

當 StorageGRID 11.7 升級期間停止儲存節點時、可能會觸發 * ILM 放置無法達成 * 警示。升級完成後、此警示可能會持續1天。

升級完成後、您可以從 Grid Manager 儀表板選取 * 最近解決的警示 * 或 * 目前警示 * 、來檢閱任何與升級相關的警示。



== 會產生許多SNMP通知

請注意、當網格節點在升級期間停止並重新啟動時、可能會產生大量的SNMP通知。若要避免過多通知、請清除 * 啟用 SNMP 代理程式通知 * 核取方塊（ * 組態 * > * 監控 * > * SNMP 代理程式 * ）、以在開始升級之前停用 SNMP 通知。然後在升級完成後重新啟用通知。



== 組態變更受到限制


NOTE: 此清單特別適用於從 StorageGRID 11.6 升級至 StorageGRID 11.7 。如果您要升級至另一個 StorageGRID 版本、請參閱該版本升級指示中的限制變更清單。

在*啟用新功能*工作完成之前：

* 請勿變更任何網格組態。
* 請勿啟用或停用任何新功能。例如、在兩個 StorageGRID 系統都更新為 StorageGRID 11.7 之前、請勿嘗試建立網格同盟連線。
* 請勿更新 ILM 組態。否則、您可能會遇到不一致且非預期的ILM行為。
* 請勿套用 Hotfix 或恢復網格節點。
+

NOTE: 如果您需要在升級期間恢復節點、請聯絡技術支援部門。

* 升級至 StorageGRID 11.7 時、不應管理 HA 群組、 VLAN 介面或負載平衡器端點。
* 在升級至 StorageGRID 11.7 完成之前、請勿刪除任何 HA 群組。其他 HA 群組中的虛擬 IP 位址可能無法存取。


直到*最終升級步驟*工作完成為止：

* 請勿執行擴充程序。
* 請勿執行取消委任程序。




== 您無法從租戶管理程式檢視貯體詳細資料或管理貯體

在升級至 StorageGRID 11.7 期間（也就是說、當系統以混合版本環境運作時）、您無法使用租戶管理程式來檢視貯體詳細資料或管理貯體。下列其中一個錯誤會出現在Tenant Manager的「桶」頁面上：

* 升級至 11.7 時無法使用此 API 。
* 當您升級至 11.7 時、無法在租戶管理器中檢視貯體版本設定詳細資料。


此錯誤將在升級至 11.7 完成後解決。

.因應措施
11.7 升級進行中時、請使用下列工具來檢視貯體詳細資料或管理貯體、而非使用租戶管理程式：

* 若要在貯體上執行標準 S3 作業、請使用 link:../s3/operations-on-buckets.html["S3 REST API"] 或 link:../tenant/understanding-tenant-management-api.html["租戶管理API"]。
* 若要在StorageGRID 庫位上執行「視覺化」自訂作業（例如檢視和修改庫位一致性層級、啟用或停用上次存取時間更新、或設定搜尋整合）、請使用「租戶管理API」。




== TLS 加密或 SSH 組態可能會變更

如果已手動變更 TLS 加密器或 SSH 組態、或是節點之間的組態不一致、則升級後所有節點都會被覆寫為「傳統相容性」或「現代相容性」。如果您使用 `fips-ciphers.sh` 在 StorageGRID 11.6 中、通用條件原則會套用至所有節點。否則會套用舊版相容性原則。如果您需要通用準則驗證組態、則必須使用通用準則原則或 FIPS 嚴格原則。如果您未使用 `fips-ciphers.sh`，您應該在升級完成後使用新的「現代化相容性」設定。要配置加密算法，請轉至 * 配置 * > * 安全性 * > * 安全性設置 * ，然後選擇 *TLS 和 SSH 策略 * 。



== CLB 連接埠可能會轉換成負載平衡器端點

舊版連線負載平衡器（ CLB ）服務已在 StorageGRID 11.7 中移除。如果在升級預先檢查期間偵測到 CLB 組態、則會觸發 * 傳統 CLB 負載平衡器活動 Detected* 警示。如果在現有 StorageGRID 版本中為 S3 或 Swift API 設定自訂憑證、則在升級至 StorageGRID 11.7 期間、 CLB 連接埠 8082 、 8083 、 8084 和 8085 將會轉換為負載平衡器端點。

另請參閱 link:../admin/managing-load-balancing.html["負載平衡考量"]。
