---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: 在開始升級之前、您必須先確認StorageGRID 先前版本的更新已套用最新的可用修補程式、且目前已安裝舊版的。 
---
= 驗證安裝的StorageGRID 版本的資訊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在開始升級之前、您必須先確認StorageGRID 先前版本的更新已套用最新的可用修補程式、且目前已安裝舊版的。

.關於這項工作
升級至 StorageGRID 11.7 之前、您的網格必須安裝 StorageGRID 11.6 。如果您目前使用的是舊版 StorageGRID 、則必須安裝所有先前的升級檔案及其最新的 Hotfix （強烈建議）、直到您的網格目前版本為 StorageGRID 11.6._x.y_ 。

中會顯示一個可能的升級路徑 <<範例：從 11.3.0.8 版升級至 StorageGRID 11.6,範例>>。


IMPORTANT: NetApp強烈建議您在StorageGRID 升級至下一個版本之前、先為每個版本套用最新的修補程式、並針對您安裝的每個新版本套用最新的修補程式。在某些情況下、您必須套用修補程式、以避免資料遺失的風險。請參閱 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp下載StorageGRID"^] 以及每個修補程式的版本資訊、以深入瞭解。

請注意、您只需一個步驟就能執行指令碼、從11.3.0.13更新到11.4.0._y_、從11.4.0.7更新到11.5.0。_y_只需一個步驟。請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_run_combined_major_upgrade_and_hotfix_script_for_StorageGRID["NetApp知識庫：如何執行StorageGRID 針對效益的重大升級與修補程式指令碼組合"^]。

.步驟
. 使用登入Grid Manager link:../admin/web-browser-requirements.html["支援的網頁瀏覽器"]。
. 從網格管理器的頂端、選取*說明*>*關於*。
. 驗證 * 版本 * 是否為 11.6._x.y_ 。
+
在 StorageGRID 11.6._x.y_ 版本編號中：

+
** * 主要版本 * 的 _x_ 值為 0 （ 11.6.0 ）。
** * Hotfix * （如果已套用）的值為 _y_ （例如 11.6.0.1 ）。


. 如果 * 版本 * 不是 11.6._x.y_ 、請前往 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp下載StorageGRID"^] 下載每個先前版本的檔案、包括每個版本的最新修補程式。
. 取得您下載之每個版本的升級指示。接著、執行該版本的軟體升級程序、並套用該版本的最新修補程式（強烈建議）。
+
請參閱 link:../maintain/storagegrid-hotfix-procedure.html["修復程序StorageGRID"]。





== 範例：從 11.3.0.8 版升級至 StorageGRID 11.6

以下範例顯示從 StorageGRID 11.3.0.8 版升級至 11.6 版的步驟、以準備 StorageGRID 11.7 升級。


IMPORTANT: 您也可以執行指令碼來合併步驟2和步驟3（從11.3.0.13更新至11.4.0._y_）、並結合步驟4和5（從11.4.0.7更新至11.5.0。_y_）。請參閱 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_run_combined_major_upgrade_and_hotfix_script_for_StorageGRID["NetApp知識庫：如何執行StorageGRID 針對效益的重大升級與修補程式指令碼組合"^]。

請依下列順序下載並安裝軟體、以準備系統進行升級：

. 套用最新StorageGRID 的更新版的更新版本。
. 升級StorageGRID 至版本更新至版本更新。
. 套用最新StorageGRID 的更新版的更新版本。
. 升級StorageGRID 至版本更新至版本更新。
. 套用最新StorageGRID 的更新版的更新版本。
. 升級至 StorageGRID 11.6.0 主要版本。
. 套用最新的 StorageGRID 11.6.0._y_ Hotfix 。

