---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: 建立租戶群組之前、請先考量您要指派給該群組的權限。租戶管理權限可決定使用者可以使用租戶管理程式或租戶管理API執行哪些工作。使用者可以屬於一或多個群組。如果使用者屬於多個群組、則權限是累積性的。 
---
= 租戶管理權限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建立租戶群組之前、請先考量您要指派給該群組的權限。租戶管理權限可決定使用者可以使用租戶管理程式或租戶管理API執行哪些工作。使用者可以屬於一或多個群組。如果使用者屬於多個群組、則權限是累積性的。

若要登入租戶管理程式或使用租戶管理API、使用者必須屬於至少擁有一項權限的群組。所有可以登入的使用者都可以執行下列工作：

* 檢視儀表板
* 變更自己的密碼（適用於本機使用者）


對於所有權限、群組的存取模式設定會決定使用者是否可以變更設定及執行作業、或是只能檢視相關設定和功能。


NOTE: 如果使用者屬於多個群組、且任何群組設定為唯讀、則使用者將擁有所有選取設定和功能的唯讀存取權。

您可以將下列權限指派給群組。請注意、S3租戶和Swift租戶擁有不同的群組權限。

[cols="1a,3a"]
|===
| 權限 | 說明 


 a| 
root存取權
 a| 
提供租戶管理程式和租戶管理API的完整存取權限。

* 附註： * Swift 使用者必須擁有 root 存取權限、才能登入租戶帳戶。



 a| 
系統管理員
 a| 
僅限Swift租戶。提供此租戶帳戶的Swift容器和物件的完整存取權

*附註：* Swift使用者必須擁有Swift管理員權限、才能使用Swift REST API執行任何作業。



 a| 
管理您自己的 S3 認證
 a| 
可讓使用者建立及移除自己的S3存取金鑰。沒有此權限的使用者不會看到 * 儲存設備（ S3 ） * > * My S3 存取鍵 * 功能表選項。



 a| 
管理所有貯體
 a| 
* S3租戶：可讓使用者使用租戶管理程式和租戶管理API來建立及刪除S3桶、並管理租戶帳戶中所有S3桶的設定、無論S3桶或群組原則為何。
+
沒有此權限的使用者不會看到 * 「鏟斗」 * 功能表選項。

* Swift租戶：可讓Swift使用者使用租戶管理API來控制Swift Container的一致性層級。


* 注意： * 您只能從租戶管理 API 將「管理所有貯體」權限指派給 Swift 群組。您無法使用 Tenant Manager 將此權限指派給 Swift 群組。



 a| 
管理端點
 a| 
可讓使用者使用租戶管理器或租戶管理 API 來建立或編輯平台服務端點、這些端點是 StorageGRID 平台服務的目的地。

沒有此權限的使用者不會看到 * 平台服務端點 * 功能表選項。



 a| 
使用 S3 主控台管理物件
 a| 
結合「管理所有貯體」權限、可讓使用者從「貯體」頁面存取實驗 S3 主控台。擁有此權限但沒有「管理所有儲存區」權限的使用者仍可直接瀏覽至實驗 S3 主控台。

|===