---
permalink: vmware/index.html 
sidebar: sidebar 
keywords: vmware 
summary: 在StorageGRID VMware環境中安裝一套功能完善的系統包括三個主要步驟。 
---
= 安裝VMware：總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在StorageGRID VMware環境中安裝一套功能完善的系統包括三個主要步驟。

. *準備*：在規劃與準備期間、您將執行下列工作：
+
** 深入瞭解StorageGRID 有關VMware的硬體、軟體、虛擬機器、儲存設備和效能要求。
** 深入瞭解的細節 link:../network/index.html["網路連線StorageGRID"] 因此您可以適當地設定網路。
** 識別並準備您計畫用來裝載StorageGRID 您的物件網格節點的實體伺服器。
** 在您準備好的伺服器上：
+
*** 安裝VMware vSphere Hypervisor
*** 設定ESX主機
*** 安裝及設定VMware vSphere和vCenter




. *部署*：使用VMware vSphere Web Client部署網格節點。當您部署網格節點時、這些節點會建立為StorageGRID 整個系統的一部分、並連線至一或多個網路。
+
.. 使用VMware vSphere Web Client、vmdk檔案及一組.OVF檔案範本、將軟體型節點部署為您在步驟1中準備的伺服器上的虛擬機器（VM）。
.. 使用StorageGRID 「功能不整設備安裝程式」來部署StorageGRID 應用不整設備節點。
+

NOTE: StorageGRID 安裝程序不包含硬體專屬的安裝與整合指示。若要瞭解如何安裝 StorageGRID 應用裝置、請參閱 link:../installconfig/index.html["硬體安裝快速入門"] 以找出產品的相關指示。



. *組態*：部署所有節點後、請使用Grid Manager來設定網格並完成安裝。


這些指示建議在StorageGRID VMware環境中部署及設定一套標準方法。另請參閱下列替代方法的相關資訊：

* 使用deploy-vsphere-ovftool.sh Bash指令碼（可從安裝歸檔取得）、在VMware vSphere中部署網格節點。
* 使用Python組態指令碼（StorageGRID 在安裝歸檔中提供）來自動化部署和設定。
* 使用Python組態指令碼（可從安裝歸檔或StorageGRID 從《不受限設備安裝程式》取得）來自動化設備網格節點的部署與組態。
* 如果您是StorageGRID 進階的程式開發人員、請使用安裝REST API來自動化StorageGRID 安裝站台節點。

