---
permalink: rhel/index.html 
sidebar: sidebar 
keywords: red hat enterprise linux, rhel, centos linux 
summary: 在StorageGRID Red Hat Enterprise Linux（RHEL）或CentOS Linux環境中安裝支援功能系統、主要步驟有三個。 
---
= 安裝Red Hat Enterprise Linux或CentOS：總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在StorageGRID Red Hat Enterprise Linux（RHEL）或CentOS Linux環境中安裝支援功能系統、主要步驟有三個。

. *準備*：在規劃與準備期間、您將執行下列工作：
+
** 深入瞭解StorageGRID 有關不適用的硬體與儲存需求。
** 深入瞭解的細節 link:../network/index.html["網路連線StorageGRID"] 因此您可以適當地設定網路。
** 識別並準備您計畫用來裝載StorageGRID 支援您的物件網格節點的實體或虛擬伺服器。
** 在您準備好的伺服器上：
+
*** 安裝Linux
*** 設定主機網路
*** 設定主機儲存設備
*** 安裝容器引擎
*** 安裝StorageGRID 支援服務




. *部署*：使用適當的使用者介面部署網格節點。當您部署網格節點時、這些節點會建立為StorageGRID 整個系統的一部分、並連線至一或多個網路。
+
.. 使用Linux命令列和節點組態檔、在您在步驟1中準備的主機上部署軟體型網格節點。
.. 使用StorageGRID 「功能不整設備安裝程式」來部署StorageGRID 應用不整設備節點。
+

NOTE: StorageGRID 安裝程序不包含硬體專屬的安裝與整合指示。若要瞭解如何安裝 StorageGRID 應用裝置、請參閱 link:../installconfig/index.html["硬體安裝快速入門"] 以找出產品的相關指示。



. *組態*：部署所有節點後、請使用Grid Manager來設定網格並完成安裝。


這些指示建議採用標準方法來部署和設定StorageGRID 一套解決方案。另請參閱下列替代方法的相關資訊：

* 使用Ansible、Puppet或Chef等標準協調架構來安裝RHEL或CentOS、設定網路和儲存設備、安裝Container Engine和StorageGRID the支援服務、以及部署虛擬網格節點。
* 使用Python組態指令碼（StorageGRID 在安裝歸檔中提供）來自動化部署和設定。
* 使用Python組態指令碼（可從安裝歸檔或StorageGRID 從《不受限設備安裝程式》取得）來自動化設備網格節點的部署與組態。
* 如果您是StorageGRID 進階的程式開發人員、請使用安裝REST API來自動化StorageGRID 安裝站台節點。

