---
permalink: admin/grid-management-api-versioning.html 
sidebar: sidebar 
keywords: grid management api, api versioning 
summary: Grid Management API使用版本管理來支援不中斷營運的升級。 
---
= Grid Management API版本管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Grid Management API使用版本管理來支援不中斷營運的升級。

例如、此Request URL會指定API版本3。

`https://_hostname_or_ip_address_/api/v3/authorize`

當進行*不相容*的變更時、會使租戶管理API的主要版本與舊版相容。當做出*與舊版相容*的變更時、租戶管理API的次要版本會被提升。相容的變更包括新增端點或新屬性。下列範例說明如何根據所做的變更類型來提高API版本。

[cols="1a,1a,1a"]
|===
| API變更類型 | 舊版本 | 新版本 


 a| 
與舊版相容
 a| 
2.1
 a| 
2.2



 a| 
與舊版不相容
 a| 
2.1
 a| 
3.0

|===
第一次安裝StorageGRID 時、只會啟用最新版本的Grid Management API。不過、當您升級StorageGRID 至全新的功能版本的更新版時、您仍可繼續存取舊版的API、以取得至少一個StorageGRID 版本的更新功能。


NOTE: 您可以使用Grid Management API來設定支援的版本。如需詳細資訊、請參閱Swagger API文件的「config」一節。您應該在更新所有Grid Management API用戶端以使用較新版本之後、停用對較舊版本的支援。

過時的要求會以下列方式標示為已過時：

* 回應標頭為「deprecated：true」
* Json回應本文包含「deprecated」：true
* NMS.log中會新增已過時的警告。例如：
+
[listing]
----
Received call to deprecated v1 API at POST "/api/v1/authorize"
----




== 判斷目前版本支援哪些API版本

使用下列API要求傳回支援的API主要版本清單：

[listing]
----
GET https://{{IP-Address}}/api/versions
{
  "responseTime": "2019-01-10T20:41:00.845Z",
  "status": "success",
  "apiVersion": "3.0",
  "data": [
    2,
    3
  ]
}
----


== 指定要求的API版本

您可以使用路徑參數來指定API版本 (`/api/v3`）或標頭 (`Api-Version: 3`）。如果您同時提供這兩個值、則標頭值會覆寫路徑值。

[listing]
----
curl https://[IP-Address]/api/v3/grid/accounts

curl -H "Api-Version: 3" https://[IP-Address]/api/grid/accounts
----