---
permalink: admin/kms-viewing-encrypted-nodes.html 
sidebar: sidebar 
keywords: view encrypted nodes, kms nodes, appliances with kms 
summary: 您可以在StorageGRID 啟用節點加密設定的支援功能系統中檢視應用裝置節點的相關資訊。 
---
= 檢視加密節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在StorageGRID 啟用「*節點加密*」設定的支援功能系統中、檢視應用裝置節點的相關資訊。

.步驟
. 選擇*組態*>*安全性*>*金鑰管理伺服器*。
+
此時會出現「金鑰管理伺服器」頁面。「組態詳細資料」索引標籤會顯示任何已設定的金鑰管理伺服器。

. 從頁面頂端、選取 * 加密節點 * 索引標籤。
+
加密節點索引標籤會列出 StorageGRID 系統中已啟用 * 節點加密 * 設定的應用裝置節點。

. 檢閱表格中每個應用裝置節點的資訊。
+
[cols="1a,2a"]
|===
| 欄位 | 說明 


 a| 
節點名稱
 a| 
應用裝置節點的名稱。



 a| 
節點類型
 a| 
節點類型：儲存設備、管理或閘道。



 a| 
網站
 a| 
安裝節點的站台名稱。StorageGRID



 a| 
KMS 名稱
 a| 
用於節點的KMS描述性名稱。

如果沒有列出 KMS 、請選取組態詳細資料索引標籤以新增 KMS 。

link:kms-adding.html["新增金鑰管理伺服器（KMS）"]



 a| 
金鑰UID
 a| 
加密金鑰的唯一ID、用於加密及解密應用裝置節點上的資料。若要檢視整個金鑰 UID 、請將游標放在儲存格上方。

破折號（-）表示金鑰唯一碼未知、可能是因為應用裝置節點與KMS之間的連線問題。



 a| 
狀態
 a| 
KMS與應用裝置節點之間的連線狀態。如果節點已連線、時間戳記每30分鐘更新一次。變更KMS組態之後、連線狀態可能需要幾分鐘的時間才能更新。

*注意：*您必須重新整理網頁瀏覽器、才能看到新的值。

|===
. 如果「狀態」欄指出KMS問題、請立即解決問題。
+
在一般KMS作業期間、狀態將*連線至KMS *。如果節點與網格中斷連線、則會顯示節點連線狀態（管理性關閉或未知）。

+
其他狀態訊息則對應StorageGRID 於名稱相同的Ses姓名：

+
** 無法載入kms組態
** KMS連線錯誤
** 找不到kms加密金鑰名稱
** KMS加密金鑰旋轉失敗
** KMS金鑰無法解密應用裝置磁碟區
** 未設定公里


+
執行這些警示的建議動作。




CAUTION: 您必須立即解決任何問題、確保資料受到完整保護。
