---
permalink: admin/kms-viewing-details.html 
sidebar: sidebar 
keywords: view kms, view key management server 
summary: 您可以檢視StorageGRID 有關您的作業系統中每個金鑰管理伺服器（KMS）的資訊、包括伺服器和用戶端憑證的目前狀態。 
---
= 檢視KMS詳細資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以檢視StorageGRID 有關您的作業系統中每個金鑰管理伺服器（KMS）的資訊、包括伺服器和用戶端憑證的目前狀態。

.步驟
. 選擇*組態*>*安全性*>*金鑰管理伺服器*。
+
此時會出現金鑰管理伺服器頁面。組態詳細資料索引標籤會顯示任何已設定的金鑰管理伺服器。

. 檢閱表格中每個KMS的資訊。
+
[cols="1a,2a"]
|===
| 欄位 | 說明 


 a| 
KMS 名稱
 a| 
KMS的描述性名稱。



 a| 
金鑰名稱
 a| 
KMS中的核心用戶端別名StorageGRID 。



 a| 
管理的金鑰
 a| 
與KMS相關的站台。StorageGRID

此欄位會顯示特定StorageGRID 的站台名稱、或*不由其他KMS管理的站台名稱（預設KMS）。*



 a| 
主機名稱
 a| 
KMS的完整網域名稱或IP位址。

如果有兩個金鑰管理伺服器的叢集、則會列出兩個伺服器的完整網域名稱或IP位址。如果叢集中有兩個以上的金鑰管理伺服器、則會列出第一個KMS的完整網域名稱或IP位址、以及叢集中其他金鑰管理伺服器的數量。

例如： `10.10.10.10 and 10.10.10.11` 或 `10.10.10.10 and 2 others`。

若要檢視叢集中的所有主機名稱、請開啟 KMS 、然後選取 * 編輯 * 或 * 動作 * > * 編輯 * 。



 a| 
憑證過期
 a| 
伺服器憑證、選用CA憑證和用戶端憑證的目前狀態：有效、過期、即將到期或不明。

* 注意： * 取得憑證過期更新可能需要 30 分鐘的 StorageGRID 時間。您必須重新整理網頁瀏覽器、才能查看目前值。

|===
. 如果「憑證過期」為「未知」、請等待長達 30 分鐘、然後重新整理您的網頁瀏覽器。
+

NOTE: 在您新增 KMS 之後、「金鑰管理伺服器」頁面上的憑證到期日會立即顯示為「未知」。可能需要StorageGRID 30分鐘才能取得每個憑證的實際狀態。您必須重新整理網頁瀏覽器、才能查看實際狀態。

. 如果「憑證過期」欄顯示憑證已過期或即將過期、請盡快解決此問題。
+
當觸發 *KMS CA 憑證過期 * 、 *KMS 用戶端憑證過期 * 和 *KMS 伺服器憑證過期 * 警示時、請記下每個警示的說明、然後執行建議的動作。

+

CAUTION: 您必須盡快解決任何憑證問題、才能維持資料存取。

. 若要檢視此 KMS 的憑證詳細資料、請從表格中選取 KMS 名稱。
. 在 KMS 摘要頁面上、檢閱伺服器憑證和用戶端憑證的中繼資料和憑證 PEM 。視需要選取 * 編輯憑證 * 以新憑證取代憑證。

