---
permalink: admin/reviewing-storagegrid-encryption-methods.html 
sidebar: sidebar 
keywords: encryption, encrypting data, best practices 
summary: StorageGRID 提供數種加密資料的選項。您應該檢閱可用的方法、以判斷哪些方法符合您的資料保護需求。 
---
= 檢閱StorageGRID 功能加密方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 提供數種加密資料的選項。您應該檢閱可用的方法、以判斷哪些方法符合您的資料保護需求。

下表提供StorageGRID 有關支援的加密方法的高階摘要。

[cols="1a,1a,1a"]
|===
| 加密選項 | 運作方式 | 適用於 


 a| 
Grid Manager中的金鑰管理伺服器（KMS）
 a| 
您 link:kms-configuring.html["設定金鑰管理伺服器"] 適用於 StorageGRID 網站和 link:../installconfig/optional-enabling-node-encryption.html["啟用應用裝置的節點加密"]。然後、應用裝置節點會連線至KMS、以要求金鑰加密金鑰（KEK）。此金鑰會加密及解密每個Volume上的資料加密金鑰（DEK）。
 a| 
安裝期間啟用*節點加密*的應用裝置節點。應用裝置上的所有資料都能受到保護、避免資料中心的實體遺失或移除。可搭配StorageGRID 部分不含資料的儲存設備和服務設備使用。



 a| 
在《支援資料保護系統》中提升安全性SANtricity
 a| 
如果 SG5700 或 SG6000 儲存設備已啟用磁碟機安全功能、您可以使用 link:../installconfig/accessing-and-configuring-santricity-system-manager.html["系統管理程式SANtricity"] 以建立及管理安全金鑰。存取受保護磁碟機上的資料需要金鑰。
 a| 
具有全磁碟加密（ FDE ）磁碟機或 FIPS 磁碟機的儲存設備。安全磁碟機上的所有資料都能受到保護、避免實體遺失或從資料中心移除。無法與某些儲存設備或任何服務應用裝置搭配使用。



 a| 
儲存的物件加密
 a| 
您可以啟用 link:changing-network-options-object-encryption.html["儲存的物件加密"] Grid Manager 中的選項。啟用時、在貯體層級或物件層級未加密的任何新物件、都會在擷取期間加密。
 a| 
新擷取的S3和Swift物件資料。

現有儲存的物件不會加密。物件中繼資料和其他敏感資料不會加密。



 a| 
S3儲存區加密
 a| 
您發出一個「放入庫位」加密要求、以啟用庫位加密。在物件層級未加密的任何新物件、都會在擷取期間加密。
 a| 
僅限新擷取的S3物件資料。

必須為儲存區指定加密。現有的貯體物件不會加密。物件中繼資料和其他敏感資料不會加密。

link:../s3/operations-on-buckets.html["在貯體上作業"]



 a| 
S3物件伺服器端加密（SSe）
 a| 
您發出S3要求來儲存物件並納入 `x-amz-server-side-encryption` 要求標頭：
 a| 
僅限新擷取的S3物件資料。

必須為物件指定加密。物件中繼資料和其他敏感資料不會加密。

可管理金鑰。StorageGRID

link:../s3/using-server-side-encryption.html["使用伺服器端加密"]



 a| 
S3物件伺服器端加密、使用客戶提供的金鑰（SSE-C）
 a| 
您發出S3要求以儲存物件、並包含三個要求標頭。

* `x-amz-server-side-encryption-customer-algorithm`
* `x-amz-server-side-encryption-customer-key`
* `x-amz-server-side-encryption-customer-key-MD5`

 a| 
僅限新擷取的S3物件資料。

必須為物件指定加密。物件中繼資料和其他敏感資料不會加密。

金鑰是在StorageGRID 非功能性的範圍內管理。

link:../s3/using-server-side-encryption.html["使用伺服器端加密"]



 a| 
外部Volume或資料存放區加密
 a| 
如果StorageGRID 您的部署平台支援、您可以使用不屬於支援的加密方法來加密整個磁碟區或資料存放區。
 a| 
所有物件資料、中繼資料和系統組態資料、假設每個磁碟區或資料存放區都已加密。

外部加密方法可更嚴密地控制加密演算法和金鑰。可與其他列出的方法結合使用。



 a| 
物件加密不StorageGRID 包括在內
 a| 
您可以在StorageGRID 物件資料和中繼資料被擷取到StorageGRID 資料之前、使用非功能性的加密方法來加密物件資料和中繼資料。
 a| 
僅限物件資料和中繼資料（系統組態資料未加密）。

外部加密方法可更嚴密地控制加密演算法和金鑰。可與其他列出的方法結合使用。

https://["Amazon Simple Storage Service -開發人員指南：使用用戶端加密來保護資料"^]

|===


== 使用多種加密方法

視您的需求而定、您一次可以使用多種加密方法。例如：

* 您可以使用KMS來保護應用裝置節點、也可以使用SANtricity 支援系統管理程式中的磁碟機安全功能、在同一個應用裝置中的自我加密磁碟機上「雙重加密」資料。
* 您可以使用 KMS 來保護應用裝置節點上的資料、也可以使用儲存的物件加密選項來加密擷取的所有物件。


如果只有一小部分物件需要加密、請考慮改為在儲存區或個別物件層級控制加密。啟用多層加密會增加效能成本。
