---
permalink: admin/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: 管理節點提供系統組態、監控及記錄等管理服務。每個網格都必須有一個主要管理節點、而且可能有任意數量的非主要管理節點來提供備援。 
---
= 什麼是管理節點？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理節點提供系統組態、監控及記錄等管理服務。每個網格都必須有一個主要管理節點、而且可能有任意數量的非主要管理節點來提供備援。

當您登入Grid Manager或租戶管理程式時、即連線至管理節點。您可以連線至任何管理節點、每個管理節點都會顯示StorageGRID 類似的畫面、顯示有關該系統的資訊。不過、維護程序必須使用主要管理節點來執行。

管理節點也可用於負載平衡S3和Swift用戶端流量。



== 偏好的寄件者是什麼

如果您的 StorageGRID 部署包含多個管理節點、則主要管理節點是警示通知、 AutoSupport 訊息、 SNMP 設陷和通知、以及舊版警示通知的首選寄件者。

在正常的系統作業下、只有偏好的傳送者會傳送通知。不過、所有其他的管理節點都會監控偏好的寄件者。如果偵測到問題、其他管理節點會做為 _ 待命寄件者 _ 。

在下列情況下、可能會傳送多個通知：

* 如果管理節點彼此「中斷」、偏好的寄件者和待命寄件者都會嘗試傳送通知、而且可能會收到多份通知複本。
* 如果待命傳送者偵測到偏好的傳送者有問題、並開始傳送通知、偏好的傳送者可能會重新獲得傳送通知的能力。如果發生這種情況、可能會傳送重複的通知。當待命傳送者不再偵測到偏好的傳送者錯誤時、它將停止傳送通知。
+

NOTE: 當您測試 AutoSupport 訊息時、所有管理節點都會傳送測試電子郵件。測試警示通知時、您必須登入每個管理節點以驗證連線能力。





== 管理節點的主要服務

下表顯示管理節點的主要服務、但此表並未列出所有節點服務。

[cols="1a,2a"]
|===
| 服務 | 按鍵功能 


 a| 
稽核管理系統（AMS）
 a| 
追蹤系統活動和事件。



 a| 
組態管理節點（CMN）
 a| 
管理全系統組態。僅主管理節點。



 a| 
管理應用程式程式介面（mgmt-API）
 a| 
處理來自Grid Management API和租戶管理API的要求。



 a| 
高可用度
 a| 
管理管理節點和閘道節點群組的高可用度虛擬IP位址。

*附註：*此服務也可在閘道節點上找到。



 a| 
負載平衡器
 a| 
提供從用戶端到儲存節點的S3和Swift流量負載平衡。

*附註：*此服務也可在閘道節點上找到。



 a| 
網路管理系統（NMS）
 a| 
提供Grid Manager的功能。



 a| 
Prometheus
 a| 
從所有節點上的服務收集和儲存時間序列度量。



 a| 
伺服器狀態監視器（SSM）
 a| 
監控作業系統和基礎硬體。

|===