---
permalink: admin/what-archive-node-is.html 
sidebar: sidebar 
keywords: archive node 
summary: 您也可以選擇StorageGRID 使用歸檔節點來部署每個資料中心站台、以便連線至目標外部歸檔儲存系統、例如Tivoli Storage Manager（TSM）。 
---
= 什麼是歸檔節點？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您也可以選擇StorageGRID 使用歸檔節點來部署每個資料中心站台、以便連線至目標外部歸檔儲存系統、例如Tivoli Storage Manager（TSM）。

[CAUTION]
====
對歸檔節點的支援（使用 S3 API 歸檔至雲端、以及使用 TSM 中介軟體歸檔至磁帶）已過時、將於未來版本中移除。將物件從歸檔節點移至外部歸檔儲存系統已由 ILM Cloud Storage Pool 取代、提供更多功能。

請參閱：

* link:../admin/migrating-objects-from-cloud-tiering-s3-to-cloud-storage-pool.html["將物件移轉至雲端儲存池"]
* link:../ilm/what-cloud-storage-pool-is.html["使用雲端儲存資源池"]


此外、您應該從 StorageGRID 11.7 或更早版本的主動式 ILM 原則中移除歸檔節點。移除儲存在保存節點上的物件資料、可簡化未來的升級作業。請參閱 link:../ilm/working-with-ilm-rules-and-ilm-policies.html["使用ILM規則和ILM原則"]。

====
歸檔節點提供一個介面、您可以透過這個介面鎖定外部歸檔儲存系統、以長期儲存物件資料。歸檔節點也會監控此連線、以及StorageGRID 物件資料在整個系統與目標外部歸檔儲存系統之間的傳輸。

設定外部目標的連線之後、您可以設定歸檔節點以最佳化TSM效能、在TSM伺服器即將達到容量或無法使用時、讓歸檔節點離線、以及設定複寫和擷取設定。您也可以設定歸檔節點的自訂警示。

無法刪除但無法定期存取的物件資料、可隨時從儲存節點的旋轉磁碟移至雲端或磁帶等外部歸檔儲存設備。此物件資料歸檔是透過設定資料中心站台的歸檔節點、然後設定ILM規則、將此歸檔節點選取為內容放置指示的「目標」。歸檔節點不會自行管理歸檔的物件資料、這是由外部歸檔裝置所達成。


NOTE: 物件中繼資料不會歸檔、但會保留在儲存節點上。



== 什麼是ARC服務

歸檔節點上的歸檔（ARC）服務提供管理介面、可用來設定外部歸檔儲存設備的連線、例如透過TSM中介軟體建立的磁帶。

這項服務可與外部歸檔儲存系統互動、傳送近線儲存的物件資料、以及在用戶端應用程式要求歸檔物件時執行擷取。當用戶端應用程式要求歸檔物件時、儲存節點會從ARC服務要求物件資料。ARC服務會向外部歸檔儲存系統提出要求、以擷取要求的物件資料、然後將其傳送至ARC服務。ARC服務會驗證物件資料、並將其轉送至儲存節點、然後再將物件傳回要求的用戶端應用程式。

透過TSM中介軟體將物件資料歸檔至磁帶的要求、將會加以管理、以提高檢索效率。您可以訂購要求、以相同的順序要求以連續順序儲存在磁帶上的物件。然後將要求排入佇列、以便提交至儲存設備。視歸檔裝置而定、可同時處理不同磁碟區上的多個物件要求。
