---
permalink: s3/post-object-restore.html 
sidebar: sidebar 
keywords: post, post object restore, object 
summary: 您可以使用S3 POST物件還原要求來還原儲存在雲端儲存池中的物件。 
---
= POST物件還原
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用S3 POST物件還原要求來還原儲存在雲端儲存池中的物件。



== 支援的要求類型

僅支援POST物件還原要求以還原物件。StorageGRID它不支援 `SELECT` 還原類型。選取「要求傳回」 `XNotImplemented`。



== 版本管理

或者、請指定 `versionId` 還原版本化儲存區中物件的特定版本。如果您沒有指定 `versionId`，則會還原物件的最新版本



== 在Cloud Storage Pool物件上進行物件後還原的行為

如果物件儲存在Cloud Storage Pool中（請參閱使用資訊生命週期管理來管理物件的指示）、則根據物件的狀態、POST物件還原要求會出現下列行為。如需詳細資訊、請參閱「標頭物件」。


NOTE: 如果物件儲存在雲端儲存資源池中、而且網格上也存在物件的一或多個複本、就不需要發出物件後還原要求來還原物件。相反地、您可以使用「取得物件」要求、直接擷取本機複本。

[cols="1a,2a"]
|===
| 物件狀態 | POST物件還原的行為 


 a| 
物件擷取至StorageGRID 不受ILM評估、或物件不在雲端儲存資源池中
 a| 
`403 Forbidden`、 `InvalidObjectState`



 a| 
Cloud Storage Pool中的物件、但尚未轉換為無法擷取的狀態
 a| 
`200 OK` 不會進行任何變更。

* 注意 * ：在物件轉換為不可擷取的狀態之前、您無法變更物件 `expiry-date`。



 a| 
物件移轉至無法擷取的狀態
 a| 
`202 Accepted` 將物件的可擷取複本還原至Cloud Storage Pool、直到要求本文指定的天數。在此期間結束時、物件會返回無法擷取的狀態。

您也可以選擇使用 `Tier` 要求元素以決定還原工作完成所需的時間 (`Expedited`、 `Standard`或 `Bulk`）。如果您沒有指定 `Tier`、 `Standard` 使用階層。

* 重要 * ：如果物件已移轉至 S3 Glacier Deep Archive 、或雲端儲存池使用 Azure Blob 儲存設備、則無法使用還原 `Expedited` 層級。傳回下列錯誤 `403 Forbidden`、 `InvalidTier`： `Retrieval option is not supported by this storage class`。



 a| 
正在從無法擷取的狀態還原的物件
 a| 
`409 Conflict`、 `RestoreAlreadyInProgress`



 a| 
物件已完全還原至雲端儲存資源池
 a| 
`200 OK`

*附註：*如果物件已還原為可擷取的狀態、您可以變更物件 `expiry-date` 以新的值重新發出POST物件還原要求 `Days`。還原日期會根據申請時間而更新。

|===
.相關資訊
link:../ilm/index.html["使用ILM管理物件"]

link:head-object.html["標頭物件"]

link:s3-operations-tracked-in-audit-logs.html["在稽核記錄中追蹤S3作業"]
