---
permalink: s3/upload-part-copy.html 
sidebar: sidebar 
keywords: upload part, upload part - copy, multipart uploads, uploads, 
summary: 「上傳零件-複製」作業會將現有物件的資料複製為資料來源、藉此上傳物件的一部分。 
---
= 上傳零件-複製
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「上傳零件-複製」作業會將現有物件的資料複製為資料來源、藉此上傳物件的一部分。

「上傳零件-複製」作業會在所有Amazon S3 REST API行為下執行。如有變更、恕不另行通知。

此要求會讀取及寫入中指定的物件資料 `x-amz-copy-source-range` 在整個系統中StorageGRID 。

支援下列要求標頭：

* `x-amz-copy-source-if-match`
* `x-amz-copy-source-if-none-match`
* `x-amz-copy-source-if-unmodified-since`
* `x-amz-copy-source-if-modified-since`




== 要求伺服器端加密的標頭

如果您為「初始化多重成分上傳」要求指定SSE-C加密、則您也必須在每個「上傳成分-複製」要求中包含下列要求標頭：

* `x-amz-server-side-encryption-customer-algorithm`：指定 `AES256`。
* `x-amz-server-side-encryption-customer-key`：指定您在「初始化多部份上傳」要求中提供的相同加密金鑰。
* `x-amz-server-side-encryption-customer-key-MD5`：指定您在「初始化多部份上傳」要求中提供的相同的MD5摘要。


如果來源物件是使用客戶提供的金鑰（SSE-C）加密、您必須在「上傳零件-複製」要求中包含下列三個標頭、以便解密物件、然後複製：

* `x-amz-copy-source​-server-side​-encryption​-customer-algorithm`：指定 `AES256`。
* `x-amz-copy-source​-server-side-encryption-customer-key`：指定在創建源對象時提供的加密密鑰。
* `x-amz-copy-source​-server-side-encryption-customer-key-MD5`：指定在創建源對象時提供的md5摘要。



IMPORTANT: 您提供的加密金鑰永遠不會儲存。如果您遺失加密金鑰、就會遺失對應的物件。在使用客戶提供的金鑰來保護物件資料之前、請先檢閱「使用伺服器端加密」中的考量事項。



== 版本管理

多部分上傳包含不同的作業、可用於初始化上傳、列出上傳內容、上傳零件、組裝上傳的零件、以及完成上傳。執行完整的「多重組件上傳」作業時、會建立物件（並在適用情況下建立版本）。
