---
permalink: monitor/considerations-for-external-syslog-server.html 
sidebar: sidebar 
keywords: syslog server, external syslog server, sizing, sizing syslog server, audit messages 
summary: 請使用下列準則來預估外部syslog伺服器需要的容量。 
---
= 外部syslog伺服器的考量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
請使用下列準則來預估您所需的外部syslog伺服器大小。



== 什麼是外部syslog伺服器？

外部syslog伺服器是StorageGRID 指不屬於功能區的伺服器、可用來在單一位置收集系統稽核資訊。使用外部syslog伺服器、您可以設定稽核資訊的目的地、以便減少管理節點上的網路流量、並更有效率地管理資訊。您可以傳送至外部syslog伺服器的稽核資訊類型包括：

* 稽核日誌包含正常系統作業期間所產生的稽核訊息
* 安全性相關事件、例如登入和升級至root
* 如果需要開啟支援案例來疑難排解您遇到的問題、可能會要求的應用程式記錄




== 如何預估外部syslog伺服器的大小

一般而言、網格的大小可達到所需的處理量、定義為每秒S3作業量或每秒位元組數。例如、您可能需要網格處理每秒1、000次S3作業、或每秒2、000 MB的物件擷取和擷取作業。您應該根據網格的資料需求來調整外部syslog伺服器的大小。

本節提供一些啟發式公式、可協助您預估外部syslog伺服器需要處理的各種類型的記錄訊息速率和平均大小、以網格的已知或所需效能特性表示（每秒S3作業數）。



=== 在預估公式中使用S3作業/秒

如果網格的處理量大小是以每秒位元組數表示、您必須將此規模轉換為每秒S3作業、才能使用估計公式。若要轉換網格處理量、您必須先判斷平均物件大小、以便使用現有稽核記錄和指標（如果有）中的資訊、或是運用您對StorageGRID 使用物件的應用程式所擁有的知識。例如、如果您的網格大小達到每秒2、000 MB的處理量、而且平均物件大小為2 MB、那麼您的網格大小就能處理每秒1、000次S3作業（2、000 MB / 2 MB）。


NOTE: 下列各節中的外部syslog伺服器規模調整公式提供一般案例預估（而非最糟案例預估）。視組態和工作負載而定、系統記錄訊息或系統記錄資料量的速率可能高於或低於公式所預測的速率。公式只能用作準則。



=== 稽核記錄的估計公式

如果您沒有S3工作負載的相關資訊、而非預期網格支援的每秒S3作業數量、您可以使用下列公式來預估外部syslog伺服器需要處理的稽核記錄數量： 假設您將「稽核層級」設為預設值（所有類別均設為「正常」、但「儲存設備」設為「錯誤」除外）：

[listing]
----
Audit Log Rate = 2 x S3 Operations Rate
Audit Log Average Size = 800 bytes
----
例如、如果您的網格大小為每秒1、000次S3作業、則外部syslog伺服器的大小應可支援每秒2、000個syslog訊息、而且應能以每秒1.6 MB的速率接收（及儲存）稽核記錄資料。

如果您對工作負載有更深入的瞭解、就有可能進行更精確的評估。在稽核記錄中、最重要的其他變數是S3作業所佔的百分比（相對於（表中使用的4個字元縮寫為稽核記錄欄位名稱）、以及下列S3欄位的平均大小（以位元組為單位）：

[cols="1a,1a,1a"]
|===
| 程式碼 | 欄位 | 說明 


 a| 
SACC
 a| 
S3租戶帳戶名稱（要求寄件者）
 a| 
傳送要求之使用者的租戶帳戶名稱。匿名要求為空白。



 a| 
小型企業
 a| 
S3租戶帳戶名稱（庫位擁有者）
 a| 
庫位擁有者的租戶帳戶名稱。用於識別跨帳戶或匿名存取。



 a| 
S3BK
 a| 
S3時段
 a| 
S3儲存區名稱。



 a| 
S3KY
 a| 
S3金鑰
 a| 
S3金鑰名稱、不含儲存區名稱。貯體的作業不包括此欄位。

|===
讓我們使用P來表示S3作業所佔的百分比、其中0≤P≤1（因此、對於100%負載工作負載、P = 1、對於100%取得工作負載、P = 0）。

讓我們用K來表示S3帳戶名稱、S3儲存區和S3金鑰總和的平均大小。假設S3帳戶名稱一律為my-S3帳戶（13位元組）、儲存區具有固定長度的名稱、例如/my/application/bucke-12345（28位元組）、而且物件具有固定長度的金鑰、例如5733a5d7-f069-41ef-8fbd-13247494c69c（36位元組）。然後K值為90（13 + 13 + 28 + 36）。

如果您可以判斷P和K的值、您可以使用下列公式預估外部syslog伺服器需要處理的稽核記錄數量、前提是您將稽核層級設為預設值（所有類別均設為「正常」、儲存除外、 設定為「錯誤」）：

[listing]
----
Audit Log Rate = ((2 x P) + (1 - P)) x S3 Operations Rate
Audit Log Average Size = (570 + K) bytes
----
例如、如果您的網格大小為每秒1、000次S3作業、則您的工作負載為50%、您的S3帳戶名稱、儲存區名稱、 而且物件名稱平均為90位元組、外部syslog伺服器的大小應可支援每秒1、500則syslog訊息、而且應能以每秒約1 MB的速率接收（及儲存）稽核記錄資料。



=== 非預設稽核層級的估計公式

提供給稽核記錄的公式會假設使用預設的稽核層級設定（所有類別均設定為「正常」、但儲存區設為「錯誤」除外）。對於非預設稽核層級設定、無法使用估算稽核訊息速率和平均大小的詳細公式。不過、下表可用於粗略估計費率； 您可以使用提供給稽核記錄的平均大小公式、但請注意、這可能會導致預估過度、因為「額外」稽核訊息平均比預設稽核訊息小。

[cols="1a,1a"]
|===
| 條件 | 公式 


 a| 
複寫：稽核層級全部設為「偵錯」或「正常」
 a| 
稽核記錄率= 8 x S3作業率



 a| 
銷毀編碼：稽核層級全部設為「除錯」或「正常」
 a| 
使用與預設設定相同的公式

|===


=== 安全性事件的估計公式

安全事件與 S3 作業無關、通常會產生可忽略的記錄和資料量。因此、我們不會提供任何預估公式。



=== 應用程式記錄的估計公式

如果您沒有S3工作負載的相關資訊、而不是預期網格支援的每秒S3作業數量、您可以使用下列公式來預估外部syslog伺服器需要處理的應用程式記錄數量：

[listing]
----
Application Log Rate = 3.3 x S3 Operations Rate
Application Log Average Size = 350 bytes
----
例如、如果您的網格大小為每秒1、000次S3作業、則外部syslog伺服器的大小應可支援每秒3、300個應用程式記錄、並能以每秒1.2 MB的速率接收（及儲存）應用程式記錄資料。

如果您對工作負載有更深入的瞭解、就有可能進行更精確的評估。對於應用程式記錄、最重要的其他變數是資料保護策略（複寫與銷毀編碼）、所放置S3作業的百分比（與獲得/其他）、以及下列S3欄位的平均大小（以位元組為單位）（表中使用的4個字元縮寫為稽核記錄欄位名稱）：

[cols="1a,1a,1a"]
|===
| 程式碼 | 欄位 | 說明 


 a| 
SACC
 a| 
S3租戶帳戶名稱（要求寄件者）
 a| 
傳送要求之使用者的租戶帳戶名稱。匿名要求為空白。



 a| 
小型企業
 a| 
S3租戶帳戶名稱（庫位擁有者）
 a| 
庫位擁有者的租戶帳戶名稱。用於識別跨帳戶或匿名存取。



 a| 
S3BK
 a| 
S3時段
 a| 
S3儲存區名稱。



 a| 
S3KY
 a| 
S3金鑰
 a| 
S3金鑰名稱、不含儲存區名稱。貯體的作業不包括此欄位。

|===


== 規模估算範例

本節說明如何使用下列資料保護方法來使用網格的估計公式範例：

* 複寫
* 銷毀編碼




=== 如果您使用複寫來保護資料

讓P代表S3作業所放置的百分比、其中0≤P≤1（因此、對於100%投入工作負載、P = 1、對於100%取得工作負載、P = 0）。

讓K代表S3帳戶名稱、S3儲存區和S3金鑰總和的平均大小。假設S3帳戶名稱一律為my-S3帳戶（13位元組）、儲存區具有固定長度的名稱、例如/my/application/bucke-12345（28位元組）、而且物件具有固定長度的金鑰、例如5733a5d7-f069-41ef-8fbd-13247494c69c（36位元組）。然後K值為90（13 + 13 + 28 + 36）。

如果您可以判斷P和K的值、您可以預估外部syslog伺服器必須使用下列公式才能處理的應用程式記錄數量。

[listing]
----
Application Log Rate = ((1.1 x P) + (2.5 x (1 - P))) x S3 Operations Rate
Application Log Average Size = (P x (220 + K)) + ((1 - P) x (240 + (0.2 x K))) Bytes
----
例如、如果您的網格大小為每秒1、000次S3作業、工作負載為50%、S3帳戶名稱、儲存區名稱及物件名稱平均為90個位元組、則外部syslog伺服器的大小應可支援每秒1800個應用程式記錄、 並以每秒0.5 MB的速率接收（通常是儲存）應用程式資料。



=== 如果您使用銷毀編碼來保護資料

讓P代表S3作業所放置的百分比、其中0≤P≤1（因此、對於100%投入工作負載、P = 1、對於100%取得工作負載、P = 0）。

讓K代表S3帳戶名稱、S3儲存區和S3金鑰總和的平均大小。假設S3帳戶名稱一律為my-S3帳戶（13位元組）、儲存區具有固定長度的名稱、例如/my/application/bucke-12345（28位元組）、而且物件具有固定長度的金鑰、例如5733a5d7-f069-41ef-8fbd-13247494c69c（36位元組）。然後K值為90（13 + 13 + 28 + 36）。

如果您可以判斷P和K的值、您可以預估外部syslog伺服器必須使用下列公式才能處理的應用程式記錄數量。

[listing]
----
Application Log Rate = ((3.2 x P) + (1.3 x (1 - P))) x S3 Operations Rate
Application Log Average Size = (P x (240 + (0.4 x K))) + ((1 - P) x (185 + (0.9 x K))) Bytes
----
例如、如果您的網格大小為每秒1、000次S3作業、則您的工作負載為50%、您的S3帳戶名稱、儲存區名稱、 物件名稱平均為90個位元組、您的外部syslog伺服器的大小應可支援每秒2、250個應用程式記錄、且應能以每秒0.6 MB的速率接收（通常是儲存）應用程式資料。

如需設定稽核訊息層級和外部 Syslog 伺服器的詳細資訊、請參閱下列內容：

* link:../monitor/configuring-syslog-server.html["設定外部syslog伺服器"]
* link:../monitor/configure-audit-messages.html["設定稽核訊息和記錄目的地"]

