---
permalink: maintain/considerations-for-decommissioning-storage-nodes.html 
sidebar: sidebar 
keywords: storagegrid, decommission 
summary: 如果您打算取消委任儲存節點、則必須瞭StorageGRID 解如何由NetApp管理該節點上的物件資料和中繼資料。 
---
= 儲存節點取消委任的考量事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您打算取消委任儲存節點、則必須瞭StorageGRID 解如何由NetApp管理該節點上的物件資料和中繼資料。

解除委任儲存節點時、需考量下列事項與限制：

* 系統必須隨時包含足夠的儲存節點、以滿足作業需求、包括ADC仲裁和作用中ILM原則。若要滿足此限制、您可能需要在擴充作業中新增儲存節點、才能取消委任現有的儲存節點。
* 如果您取消委任儲存節點時、儲存節點已中斷連線、則系統必須使用連線儲存節點的資料來重新建構資料、否則可能導致資料遺失。
* 移除儲存節點時、必須透過網路傳輸大量的物件資料。雖然這些傳輸不應影響正常的系統作業、但可能會影響StorageGRID 到整個過程中使用的網路頻寬。
* 與儲存節點解除委任相關的工作優先順序低於正常系統作業相關的工作。這表示汰換不會干擾StorageGRID 正常的非功能性系統作業、也不需要排定系統閒置一段時間。由於汰換是在背景執行、因此很難預估完成程序所需的時間。一般而言、當系統處於靜止狀態時、或一次只移除一個儲存節點時、汰換作業會更快完成。
* 取消委任儲存節點可能需要數天或數週的時間。請據此規劃此程序。雖然取消委任程序的設計不會影響系統作業、但它可能會限制其他程序。一般而言、移除網格節點之前、您應該先執行任何計畫性的系統升級或擴充。
* 涉及儲存節點的取消委任程序可在特定階段暫停、以便在需要時執行其他維護程序、並在完成後繼續執行。
* 當取消委任工作正在執行時、您無法在任何網格節點上執行資料修復作業。
* 在停用儲存節點時、您不應對ILM原則進行任何變更。
* 當您移除儲存節點時、節點上的資料會移轉至其他網格節點、但此資料不會從停用的網格節點中完全移除。若要永久且安全地移除資料、您必須在取消委任程序完成後、清除已停用的網格節點磁碟機。
* 當您取消委任儲存節點時、可能會發出下列警示和警示、您可能會收到相關的電子郵件和SNMP通知：
+
** *無法與node*警示通訊。當您取消委任包含ADC服務的儲存節點時、就會觸發此警示。取消委任作業完成後、警示便會解決。
** VSTU（物件驗證狀態）警示。此通知層級警示表示儲存節點在取消委任程序期間正進入維護模式。
** CASA（資料儲存區狀態）警示。此重大層級警示表示Cassandra資料庫因為服務停止而關閉。




.相關資訊
link:restoring-object-data-to-storage-volume.html["將物件資料還原至儲存磁碟區"]
